export const ADD_PROJECT_REQUEST= "ADD_PROJECT_REQUEST"
export const ADD_PROJECT_SUCCESS= "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAIL= "ADD_PROJECT_FAIL"

export const GET_PROJECT_REQUEST= "GET_PROJECT_REQUEST"
export const GET_PROJECT_SUCSESS= "GET_PROJECT_SUCSESS"
export const GET_PROJECT_FAIL= "GET_PROJECT_FAIL"

export const SET_EDIT_WORK = 'SET_EDIT_WORK';
export const SET_SEARCH = 'SET_SEARCH';

export const SET_SORT = 'SET_SORT';

export const GET_GRAPHDATA_ERROR = 'GET_GRAPHDATA_ERROR';
export const GET_GRAPHDATA_REQUEST = 'GET_GRAPHDATA_REQUEST';
export const GET_GRAPHDATA_SUCCESS = 'GET_GRAPHDATA_SUCCESS';

